import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { products, whatsapp, pageHead } from '@/lib/jewellery';
export const Route = createFileRoute('/consultation')({ head: () => pageHead('Bespoke & Bridal Consultation', 'Begin your personal bridal or bespoke jewellery journey with Ikashi Jewels in Hyderabad and Mumbai.'), component: Consultation });
function Consultation() {
 const [name, setName] = useState(''); const [interest, setInterest] = useState('Bridal jewellery'); const [city, setCity] = useState('Hyderabad'); const [message, setMessage] = useState('');
 return <><section className="page-heading"><p className="eyebrow">BESPOKE & BRIDAL</p><h1>Your vision.<br/><em>Our artistry.</em></h1><p>For a once-in-a-lifetime moment, nothing less than something truly yours.</p></section><section className="section-wrap consultation-grid"><div><img src={products[8].image} alt="Rajsi bridal heritage choker"/><h2>Made for your <em>forever.</em></h2><p>Whether you are curating your bridal trousseau or imagining a bespoke piece, our team will guide you through the details — style, gemstones, gold and the moments that matter.</p></div><form className="consultation-form" onSubmit={e => { e.preventDefault(); const interestText = interest.toLowerCase(); const consultText = city === 'Virtual consultation' ? 'virtual consultation' : `consultation in ${city}`; window.open(whatsapp(`Hi, This is ${name}. I would like a ${interestText} ${consultText}.${message ? ` ${message}` : ''}`), '_blank', 'noopener,noreferrer'); }}><p className="eyebrow">A PERSONAL INVITATION</p><h2>Let’s create <em>something beautiful.</em></h2><label>Your name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" autoComplete="name"/></label><label>I’m interested in<select value={interest} onChange={e=>setInterest(e.target.value)}><option>Bridal jewellery</option><option>Bespoke jewellery</option><option>Collection enquiry</option></select></label><label>Preferred city<select value={city} onChange={e=>setCity(e.target.value)}><option>Hyderabad</option><option>Mumbai</option><option>Virtual consultation</option></select></label><label>Tell us about your vision<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Your occasion, preferred style, or a piece you have in mind…" rows={4}/></label><Button type="submit" className="gold-button">Request Consultation on WhatsApp<ArrowUpRight/></Button><p className="small-note">Continue your consultation directly with our team on WhatsApp.</p></form></section></>;
}