import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { products, pageHead } from '@/lib/jewellery';
import { ProductCard, TrustStrip, ConsultationBand } from '@/components/jewellery';
export const Route = createFileRoute('/')({ head: () => pageHead('Natural Diamonds & Fine Jewellery', 'Ikashi Jewels — For the Muse in You. Discover natural diamonds, fine gold and bridal jewellery in Hyderabad and Mumbai.'), component: Index });
function Index() {
 return <><section className="home-hero"><img className="hero-photo" src={products[0].image} alt="Emerald and diamond necklace set displayed on green velvet"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">IKASHI JEWELS · NATURAL DIAMONDS</p><h1>For the<br/><em>Muse in You</em></h1><div className="hero-rule"/><p>Not just worn. Felt. Remembered.<br/>Extraordinary jewellery for your extraordinary story.</p><Button asChild className="gold-button"><Link to="/collections">Explore the Collections<ArrowUpRight/></Link></Button><span className="hero-caption">NATURAL DIAMONDS & FINE GOLD JEWELLERY</span></div><div className="hero-footnote"><span>THE EMERALD HEIRLOOM</span><Link to="/collections/$productId" params={{ productId: 'emerald-heirloom' }}>Discover the piece <ArrowUpRight size={16}/></Link></div></section><TrustStrip/><section className="section-wrap home-collections"><div className="section-title title-row"><div><p className="eyebrow">A WORLD OF IKASHI</p><h2>Timeless by nature.<br/><em>Unmistakably you.</em></h2></div><Link to="/collections" className="text-link">Discover All Collections<ArrowRight size={18}/></Link></div><div className="category-showcase">{[{name:'Necklaces & Sets',p:products[6]},{name:'Earrings & Jhumkas',p:products[2]},{name:'Bangles & Bracelets',p:products[1]},{name:'Bridal Couture',p:products[8]}].map(({name,p})=><Link to="/collections" key={name} className="category-tile"><img src={p.image} alt={name} loading="lazy"/><div><h3>{name}</h3><ArrowUpRight size={21}/></div></Link>)}</div></section><section className="signature-section section-wrap"><div className="section-title title-row"><div><p className="eyebrow">THE SIGNATURE EDIT</p><h2>Pieces to <em>fall for.</em></h2></div><p>Handpicked beauty. Enduring brilliance.</p></div><div className="product-grid">{[products[0],products[3],products[7]].map(p=><ProductCard key={p.id} product={p}/>)}</div></section><section className="home-story"><img src={products[4].image} alt="Muse emerald earrings worn for a special occasion" loading="lazy"/><div><p className="eyebrow">MORE THAN JEWELLERY</p><h2>A reflection of you.<br/><em>A legacy of love.</em></h2><p>Rooted in Indian artistry and inspired by the modern muse, Ikashi brings together natural diamonds, fine gold and a devotion to the exceptional.</p><p>From your everyday moments to your bridal chapter — we craft pieces to become a part of your story.</p><Link to="/about" className="text-link">The Ikashi Story<ArrowRight size={18}/></Link></div></section><ConsultationBand/></>;
}
